apiVersion: v1
kind: Service
metadata:
  name: "humongous-healthcare-api"
  labels:
    app: "humongous-healthcare-api"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "humongous-healthcare-api"